/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Health
         * @description Report that this process is alive and say which process it is.
         *
         *     Deliberately requires **no authentication**: it is what a caller reads *before* deciding to
         *     send its token, to confirm that whatever holds the discovered port is this companion and not an
         *     unrelated local server (AD-4). There is no failure path to model — a companion that cannot
         *     answer does not answer at all — so under a running lifespan the response is always ``200`` with
         *     ``status="ok"``. The lifespan is a real precondition: served without one (no supported path
         *     does), the missing ``instance_id`` is an unhandled error, not a modelled state.
         *
         *     Args:
         *         request: The incoming request, used only to reach ``app.state.instance_id``, which the
         *             lifespan minted at startup.
         *
         *     Returns:
         *         The health resource itself, unwrapped: AD-16 keeps the MCP result envelope out of REST.
         */
        get: operations["read_health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ErrorResponse
         * @description The body of every non-2xx response — the token, and nothing else (AD-16).
         *
         *     The serialised shape is exactly ``{"reason": "<token>"}``. There is deliberately **no**
         *     ``message``, ``detail``, ``status`` or ``errors[]`` field:
         *
         *     * **the copy lives in the UI.** ``EXPERIENCE.md`` fixes the verbatim wording of every state
         *       panel, and UX-DR33 bans "something went wrong"; a server-side prose field would be a second
         *       source of user-facing copy that no UX review covers.
         *     * **prose would leak input back.** FastAPI's validation detail echoes the offending value, and
         *       the companion is one ``fetch`` away from any page in the browser. The detail goes to the log.
         *     * **the token is the contract.** Anything a human needs beyond it belongs in the log. If a
         *       later story genuinely needs machine-readable specifics, it adds a *typed* optional field with
         *       a named UX consumer — not a free-text bucket.
         *
         *     What each token means on the glass, which is why the set is closed:
         *
         *     * ``deck_not_found`` — the deck the caller asked for is gone (deleted between a push and a
         *       refetch); the SPA clears to the **No-active-deck** panel.
         *     * ``database_not_initialized`` — fresh install, no card database yet; the **"Card database not
         *       set up yet."** panel, which tells the user to ask their agent to run ``initialize_database``.
         *     * ``database_unavailable`` — reads are failing transiently (a bulk refresh in flight, or an
         *       unhandled backend fault); the **"Card database is updating."** panel, which retries quietly.
         *     * ``invalid_request`` — the request itself was malformed, or aimed at a path/method/``Host``
         *       the companion does not serve. No panel of its own: the SPA never generates one, so it means
         *       a client bug or a stray caller, and the log is where it is diagnosed.
         *     * ``payload_too_large`` — an agent push exceeded the ingest cap (c5-5). Surfaced to the *agent*
         *       through the MCP tool's outcome vocabulary, not to the glass.
         *     * ``internal_error`` — the companion itself hit an unhandled bug (500). Deterministic, so the
         *       SPA must **not** quietly retry it the way ``database_unavailable`` retries; its state panel
         *       is written in Epic 2 (c2-9). The log carries the traceback; the wire carries the token.
         *
         *     Attributes:
         *         reason: The token, drawn from :data:`ErrorReason`.
         *
         *     Example:
         *         >>> ErrorResponse(reason="deck_not_found").model_dump()
         *         {'reason': 'deck_not_found'}
         */
        ErrorResponse: {
            /**
             * Reason
             * @enum {string}
             */
            reason: "deck_not_found" | "database_not_initialized" | "database_unavailable" | "invalid_request" | "payload_too_large" | "internal_error";
        };
        /**
         * HealthResponse
         * @description The body of ``GET /health`` — the companion's unauthenticated identity probe (FR-14).
         *
         *     A caller reads this *before* deciding to send its token: it confirms that whatever answered on
         *     the discovered port is this companion process and not some unrelated local server that happens
         *     to hold the port (AD-4). ``status`` is deliberately **not** the project's MCP result envelope
         *     (AD-16 bans that from REST) — the body *is* the health resource and ``status`` is a field of it.
         *
         *     Attributes:
         *         status: A closed token, extendable only by adding a member to the ``Literal``. Always
         *             ``"ok"`` today; ``/health`` has no failure path to model, since a companion that cannot
         *             answer does not answer at all.
         *         instance_id: The per-process identity minted at startup, echoed so a caller can match it
         *             against the value the discovery file advertised.
         *
         *     Example:
         *         >>> HealthResponse(status="ok", instance_id="0f6e...").status
         *         'ok'
         */
        HealthResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
            /** Instance Id */
            instance_id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    read_health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description reason: invalid_request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description reason: payload_too_large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description reason: internal_error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description reason: database_unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
